message:
  broadcast:
    # Disable broadcasting with empty string or null
    # E.g.:
    # player-packet: ""
    # system: null
    player-packet: "%Player% sent a magic packet includes {:}"
    system: "Somebody sent a chat contains {jndi:}, but we don't say who did this :P"

# Send the payload back to exploiter
repeat-back-to-exploiter: true
# Start the server forcefully when error happens.
force-start: false
